#!/bin/bash

set -e

version=$1
mpidist=mpich
mpiversion=3.2b2
mpidir=/opt/$mpidist/$mpiversion

# Download tarball
if [[ ! -e hdf5-${version}.tar.bz2 ]]; then
    wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-${version}.tar.bz2
fi

# Extract and install gcc-compiled version
tar xvf hdf5-${version}.tar.bz2
cd hdf5-${version}
CC=gcc FC=gfortran ./configure --prefix=/opt/hdf5/${version}-gnu \
    --enable-fortran --enable-fortran2003
make
make install
cd ..
rm -rf hdf5-${version}

# Extract and install Intel-compiled version
rm -rf hdf5-${version}
tar xvf hdf5-${version}.tar.bz2
cd hdf5-${version}
CC=icc FC=ifort ./configure --prefix=/opt/hdf5/${version}-intel \
    --enable-fortran --enable-fortran2003
make
make install
cd ..
rm -rf hdf5-${version}

# Extract and install gcc-compiled version
tar xvf hdf5-${version}.tar.bz2
cd hdf5-${version}
CC=${mpidir}-gnu/bin/mpicc FC=${mpidir}-gnu/bin/mpif90 \
    ./configure --prefix=/opt/phdf5/${version}-${mpidist}-${mpiversion}-gnu \
    --enable-fortran --enable-fortran2003
make
make install
cd ..
rm -rf hdf5-${version}

# Extract and install Intel-compiled version
tar xvf hdf5-${version}.tar.bz2
cd hdf5-${version}
CC=${mpidir}-intel/bin/mpicc FC=${mpidir}-intel/bin/mpif90 \
    ./configure --prefix=/opt/phdf5/${version}-${mpidist}-${mpiversion}-intel \
    --enable-fortran --enable-fortran2003
make
make install
cd ..
