#!/bin/bash

set -e

version=$1
use_system_libs=1

# Download tarballs
if [[ ! -e gcc-${version}.tar.bz2 ]]; then
    wget http://mirrors-usa.go-parts.com/gcc/releases/gcc-${version}/gcc-${version}.tar.bz2
fi

# Extract GCC source
if [[ ! -d gcc-${version} ]]; then
    tar xvf gcc-${version}.tar.bz2
fi
cd gcc-${version}

# Configure
if [[ $use_system_libs == 0 ]]; then
    ./contrib/download_prerequisites
    ./configure --prefix=/opt/gcc/${version} --disable-checking \
        --with-system-zlib --enable-threads=posix --program-suffix=-${version:0:3}
else
    ./configure --prefix=/opt/gcc/${version} --with-gmp=/usr/lib --with-mpc=/usr/lib \
        --with-mpfr=/usr/lib --disable-checking --program-suffix=-${version:0:3} \
        --with-system-zlib --enable-threads=posix
fi

# Build and install
make
make install
cd ..
