#!/bin/bash

set -e

version=$1
gnuversion=6.3
intelversion=17.0.4

# Download tarball
if [[ ! -e openmpi-${version}.tar.bz2 ]]; then
    wget http://open-mpi.org/software/ompi/v${version:0:3}/downloads/openmpi-${version}.tar.bz2
fi

# Extract and install gcc-compiled version
tar xvf openmpi-${version}.tar.bz2
cd openmpi-${version}
CC=gcc CXX=g++ FC=gfortran ./configure \
    --prefix=/opt/openmpi/${version}-gnu-${gnuversion}
make
make install
cd ..

# Extract and install Intel-compiled version
rm -rf openmpi-${version}
tar xvf openmpi-${version}.tar.bz2
cd openmpi-${version}
CC=icc CXX=icpc FC=ifort ./configure \
    --prefix=/opt/openmpi/${version}-intel-${intelversion}
make
make install
cd ..
