#!/bin/bash

set -e

version=$1
gnuversion=6.3
mpidist=mpich
mpiversion=3.2
mpidir=/opt/$mpidist/$mpiversion

# Download tarball
if [[ ! -e petsc-${version}.tar.gz ]]; then
    wget http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-${version}.tar.gz
fi

# Extract and install gcc-compiled version
tar xvf petsc-${version}.tar.gz
cd petsc-${version}
python2 ./configure --prefix=/opt/petsc/${version}-${mpidist}-${mpiversion}-gnu-${gnuversion} \
            --download-fblaslapack \
            --download-hypre \
            --download-metis \
            --download-parmetis \
            --download-superlu_dist \
            --download-mumps \
            --download-scalapack \
            --with-pic \
            --with-mpi-dir=${mpidir}-gnu-${gnuversion} \
            --with-shared-libraries \
            --with-fortran-datatypes
make
make install
cd ..
rm -rf petsc-${version}

# Extract and install Intel-compiled version
tar xvf petsc-${version}.tar.gz
cd petsc-${version}
./configure --prefix=/opt/petsc/${version}-intel \
    --with-blas-lapack-dir=/opt/intel/composerxe/mkl \
    --with-mpi-dir=${mpidir}-intel \
    --with-shared-libraries --with-fortran-datatypes
make
make install
cd ..
