#!/bin/bash

set -e

version=$1

# Download tarball
if [[ ! -e cmake-${version}.tar.gz ]]; then
   wget http://www.cmake.org/files/v${version:0:3}/cmake-${version}.tar.gz
fi

# Extract and install
tar xvf cmake-${version}.tar.gz
cd cmake-${version}
./bootstrap --prefix=/opt/cmake/${version}
make
make install
cd ..
